/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de6_number;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class Form_Number extends javax.swing.JFrame {
public Number number = new Number();
    /**
     * Creates new form Form_Number
     */
    public Form_Number() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtGtA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtGtB = new javax.swing.JTextField();
        btnCong = new javax.swing.JButton();
        btnChia = new javax.swing.JButton();
        btnTru = new javax.swing.JButton();
        btnNhan = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbKq = new javax.swing.JLabel();
        btnUCLN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gía trị A:");

        txtGtA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGtAActionPerformed(evt);
            }
        });

        jLabel2.setText("Gía trị B:");

        txtGtB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGtBActionPerformed(evt);
            }
        });

        btnCong.setText("Cộng");
        btnCong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCongActionPerformed(evt);
            }
        });

        btnChia.setText("Chia");
        btnChia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiaActionPerformed(evt);
            }
        });

        btnTru.setText("Trừ");
        btnTru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruActionPerformed(evt);
            }
        });

        btnNhan.setText("Nhân");
        btnNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanActionPerformed(evt);
            }
        });

        btnLuu.setText("Lưu trữ");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        jLabel3.setText("Kết quả:");

        btnUCLN.setText("Tìm UCLN");
        btnUCLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUCLNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29)
                        .addComponent(txtGtB, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(29, 29, 29)
                        .addComponent(txtGtA, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(140, 140, 140)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnNhan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTru, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnUCLN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLuu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jLabel3)
                        .addGap(205, 205, 205))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28)
                        .addComponent(lbKq)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGtA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCong)
                    .addComponent(btnTru)
                    .addComponent(btnLuu)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txtGtB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnChia)
                        .addComponent(btnNhan)
                        .addComponent(btnUCLN))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lbKq)))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGtAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGtAActionPerformed

    private void txtGtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGtBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGtBActionPerformed

    private void btnCongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCongActionPerformed
        if(txtGtA.getText().trim().isEmpty() || txtGtB.getText().trim().isEmpty() )
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ 2 giá trị");
        }
        else
        {
            boolean hopLe = true;
           String message = "";
           
            try {
                number.setGtA(Integer.parseInt(txtGtA.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị A không hợp lệ\n";
            }
            
            try {
                number.setGtB(Integer.parseInt(txtGtB.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị B không hợp lệ\n";
            }
            
            if(hopLe)
            {
                lbKq.setText(Integer.toString(number.cong()));
            }
            else
            {
                JOptionPane.showMessageDialog(this, message);
            }
        }
    }//GEN-LAST:event_btnCongActionPerformed

    private void btnChiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiaActionPerformed
        // TODO add your handling code here:
         if(txtGtA.getText().trim().isEmpty() || txtGtB.getText().trim().isEmpty() )
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ 2 giá trị");
        }
        else
        {
            boolean hopLe = true;
           String message = "";
           
            try {
                 number.setGtA(Integer.parseInt(txtGtA.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị A không hợp lệ\n";
            }
            
            try {
                number.setGtB(Integer.parseInt(txtGtB.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị B không hợp lệ\n";
            }
            
            if(hopLe)
            {
                lbKq.setText(Double.toString(number.chia()));
            }
            else
            {
                JOptionPane.showMessageDialog(this, message);
            }
        }
    }//GEN-LAST:event_btnChiaActionPerformed

    private void btnTruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruActionPerformed
        if(txtGtA.getText().trim().isEmpty() || txtGtB.getText().trim().isEmpty() )
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ 2 giá trị");
        }
        else
        {
            boolean hopLe = true;
           String message = "";
           
            try {
                number.setGtA(Integer.parseInt(txtGtA.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị A không hợp lệ\n";
            }
            
            try {
                number.setGtB(Integer.parseInt(txtGtB.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị B không hợp lệ\n";
            }
            
            if(hopLe)
            {
                lbKq.setText(Integer.toString(number.tru()));
            }
            else
            {
                JOptionPane.showMessageDialog(this, message);
            }
        }
    }//GEN-LAST:event_btnTruActionPerformed

    private void btnNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanActionPerformed
         if(txtGtA.getText().trim().isEmpty() || txtGtB.getText().trim().isEmpty() )
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ 2 giá trị");
        }
        else
        {
            boolean hopLe = true;
           String message = "";
           
            try {
                number.setGtA(Integer.parseInt(txtGtA.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị A không hợp lệ\n";
            }
            
            try {
                 number.setGtB(Integer.parseInt(txtGtB.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị B không hợp lệ\n";
            }
            
            if(hopLe)
            {
                lbKq.setText(Integer.toString(number.nhan()));
            }
            else
            {
                JOptionPane.showMessageDialog(this, message);
            }
        }
    }//GEN-LAST:event_btnNhanActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
         if(txtGtA.getText().trim().isEmpty() || txtGtB.getText().trim().isEmpty() )
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ 2 giá trị");
        }
        else
        {
            boolean hopLe = true;
           String message = "";
           
            try {
                number.setGtA(Integer.parseInt(txtGtA.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị A không hợp lệ\n";
            }
            
            try {
                number.setGtB(Integer.parseInt(txtGtB.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị B không hợp lệ\n";
            }
            
            if(hopLe)
            {
                try {
                    File f = new File("number.dat");
                    FileWriter fw = new FileWriter(f);
                    BufferedWriter bw = new BufferedWriter(fw);
                    
                    bw.write(number.toString());
                    bw.close();
                    fw.close();
                    JOptionPane.showMessageDialog(this, "Lưu file thành công");
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Lưu file không thành công");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, message);
            }
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnUCLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUCLNActionPerformed
         if(txtGtA.getText().trim().isEmpty() || txtGtB.getText().trim().isEmpty() )
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ 2 giá trị");
        }
        else
        {
            boolean hopLe = true;
           String message = "";
           
            try {
                 number.setGtB(Integer.parseInt(txtGtB.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị A không hợp lệ\n";
            }
            
            try {
                number.setGtB(Integer.parseInt(txtGtB.getText().trim()));
            } catch (NumberFormatException e) {
                hopLe=false;
                message+="Gía trị B không hợp lệ\n";
            }
            
            if(hopLe)
            {
                lbKq.setText(Integer.toString(number.ucln()));
            }
            else
            {
                JOptionPane.showMessageDialog(this, message);
            }
        }
    }//GEN-LAST:event_btnUCLNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Number.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Number().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChia;
    private javax.swing.JButton btnCong;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnNhan;
    private javax.swing.JButton btnTru;
    private javax.swing.JButton btnUCLN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbKq;
    private javax.swing.JTextField txtGtA;
    private javax.swing.JTextField txtGtB;
    // End of variables declaration//GEN-END:variables
}
