/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de3;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author admin
 */
public class FormSinhVien extends javax.swing.JFrame {

    /**
     * Creates new form FormSinhVien
     */
    public FormSinhVien() {
        initComponents();
        txtDonVi.setEnabled(false);
        txtHocPhi.setEnabled(false);
        txtLuong.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtMaSV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtDiemTB = new javax.swing.JTextField();
        rbNam = new javax.swing.JRadioButton();
        rbNữ = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        rbSVAT = new javax.swing.JRadioButton();
        rbSVMM = new javax.swing.JRadioButton();
        lbHocPhi = new javax.swing.JLabel();
        txtHocPhi = new javax.swing.JTextField();
        lbDonVi = new javax.swing.JLabel();
        txtDonVi = new javax.swing.JTextField();
        lbLuong = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        txtLuu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Thông tin sinh viên");

        jLabel2.setText("Mã SV:");

        jLabel3.setText("Họ tên:");

        jLabel4.setText("Ngày sinh:");

        jLabel5.setText("Địa chỉ:");

        jLabel6.setText("Giới tính:");

        jLabel7.setText("Điểm trung bình:");

        buttonGroup1.add(rbNam);
        rbNam.setText("Nam");

        buttonGroup1.add(rbNữ);
        rbNữ.setText("Nữ");

        jLabel8.setText("Loại sinh viên:");

        buttonGroup2.add(rbSVAT);
        rbSVAT.setText("Sinh viên ATTT");
        rbSVAT.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbSVATStateChanged(evt);
            }
        });
        rbSVAT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSVATActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbSVMM);
        rbSVMM.setText("Sinh viên Mật Mã");
        rbSVMM.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                rbSVMMStateChanged(evt);
            }
        });
        rbSVMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSVMMActionPerformed(evt);
            }
        });

        lbHocPhi.setText("Học phí:");

        lbDonVi.setText("Đơn vị:");

        lbLuong.setText("Lương:");

        txtLuu.setText("Lưu");
        txtLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLuuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(lbHocPhi)
                    .addComponent(lbDonVi)
                    .addComponent(lbLuong)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(72, 72, 72)
                                    .addComponent(rbNam)
                                    .addGap(91, 91, 91)
                                    .addComponent(rbNữ)
                                    .addGap(67, 67, 67))
                                .addComponent(txtDiemTB, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHocPhi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rbSVAT)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rbSVMM)))
                        .addComponent(jLabel1))
                    .addComponent(txtLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDonVi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(txtLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbNam)
                    .addComponent(rbNữ))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDiemTB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(rbSVAT)
                    .addComponent(rbSVMM))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHocPhi)
                    .addComponent(txtHocPhi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDonVi)
                    .addComponent(txtDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbLuong)
                    .addComponent(txtLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtLuu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbSVMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSVMMActionPerformed
        // TODO add your handling code here:
        txtDonVi.setText("");
        txtHocPhi.setText("");
        txtLuong.setText("");
        txtDonVi.setEnabled(true);
        txtHocPhi.setEnabled(false);
        txtLuong.setEnabled(true);
    }//GEN-LAST:event_rbSVMMActionPerformed

    private void rbSVATActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSVATActionPerformed
        // TODO add your handling code here:
        txtDonVi.setText("");
        txtHocPhi.setText("");
        txtLuong.setText("");
        txtDonVi.setEnabled(false);
        txtHocPhi.setEnabled(true);
        txtLuong.setEnabled(false);
    }//GEN-LAST:event_rbSVATActionPerformed

    private void rbSVATStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbSVATStateChanged

    }//GEN-LAST:event_rbSVATStateChanged

    private void rbSVMMStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_rbSVMMStateChanged

    }//GEN-LAST:event_rbSVMMStateChanged

    private void txtLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLuuActionPerformed
        if (txtDiaChi.getText().trim().isEmpty() || txtDiemTB.getText().trim().isEmpty() || txtHoTen.getText().trim().isEmpty()
                || txtMaSV.getText().trim().isEmpty() || txtNgaySinh.getText().trim().isEmpty() || (!rbNam.isSelected() && !rbNữ.isSelected()) || (!rbSVAT.isSelected() && !rbSVMM.isSelected())) {
            if (rbSVAT.isSelected()) {
                if (txtHocPhi.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
                }
            }
            if (rbSVMM.isSelected()) {
                if (txtLuong.getText().trim().isEmpty() || txtDonVi.getText().trim().isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
                }
            }
            if ((!rbSVAT.isSelected() && !rbSVMM.isSelected())) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            }
        } else {
            boolean hopLe = true;
            String mess = "";
            Date ngaySinh = null;
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            double diem = 0;
            double hocPhi = 0;
            double luong = 0;
            try {
                ngaySinh = sdf.parse(txtNgaySinh.getText().trim());
            } catch (Exception e) {
                hopLe = false;
                mess += "Ngày sinh không hợp lệ\n";
            }

            try {
                diem = Double.valueOf(txtDiemTB.getText().trim());
            } catch (Exception e) {
                hopLe = false;
                mess += "Điểm không hợp lệ\n";
            }
            if (diem > 10) {
                hopLe = false;
                mess += "Điểm không hợp lệ\n";
            }

            if (rbSVAT.isSelected()) {
                try {
                    hocPhi = Double.valueOf(txtHocPhi.getText().trim());
                } catch (Exception e) {
                    hopLe = false;
                    mess += "Học phí không hợp lệ\n";
                }
            }

            if (rbSVMM.isSelected()) {
                try {
                    luong = Double.valueOf(txtLuong.getText().trim());
                } catch (Exception e) {
                    hopLe = false;
                    mess += "Lương không hợp lệ\n";
                }
            }
            if (hopLe) {
                if (rbSVAT.isSelected()) {
                    try {
                        File f = new File("svat.dat");
                        FileWriter fw = new FileWriter(f, true);
                        BufferedWriter bw = new BufferedWriter(fw);
                        SinhVienATTT svat = new SinhVienATTT(hocPhi, txtMaSV.getText().trim(), txtHoTen.getText().trim(), txtDiaChi.getText().trim(), rbNam.isSelected() ? "Nam" : "Nữ", ngaySinh, diem);
                        bw.write(svat.toString());
                        bw.newLine();
                        bw.close();;
                        fw.close();

                        JOptionPane.showMessageDialog(this, "Lưu thông tin thành công");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Lưu thông tin không thành công");
                    }
                }

                if (rbSVMM.isSelected()) {
                    try {
                        File f = new File("svmm.dat");
                        FileWriter fw = new FileWriter(f, true);
                        BufferedWriter bw = new BufferedWriter(fw);
                        SinhVienMatMa svmm = new SinhVienMatMa(txtDonVi.getText().trim(), luong, txtMaSV.getText().trim(), txtHoTen.getText().trim(), txtDiaChi.getText().trim(), rbNam.isSelected() ? "Nam" : "Nữ", ngaySinh, diem);
                        bw.write(svmm.toString());
                        bw.newLine();
                        bw.close();;
                        fw.close();
                        JOptionPane.showMessageDialog(this, "Lưu thông tin thành công");
                    } catch (Exception e) {
                        JOptionPane.showMessageDialog(this, "Lưu thông tin không thành công");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, mess);
            }
        }


    }//GEN-LAST:event_txtLuuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lbDonVi;
    private javax.swing.JLabel lbHocPhi;
    private javax.swing.JLabel lbLuong;
    private javax.swing.JRadioButton rbNam;
    private javax.swing.JRadioButton rbNữ;
    private javax.swing.JRadioButton rbSVAT;
    private javax.swing.JRadioButton rbSVMM;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtDiemTB;
    private javax.swing.JTextField txtDonVi;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtHocPhi;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JButton txtLuu;
    private javax.swing.JTextField txtMaSV;
    private javax.swing.JTextField txtNgaySinh;
    // End of variables declaration//GEN-END:variables
}
